"""Report writers. Every number a reader might quote comes from here, and every one is generated.

The reports are committed so the repository can be read without being run, and regenerated by CI on
every push so a stale number fails the build rather than sitting there being wrong.
"""

from __future__ import annotations

import json
from pathlib import Path


def _table(headers: list[str], rows: list[list]) -> str:
    lines = ["| " + " | ".join(headers) + " |", "|" + "|".join(["---"] * len(headers)) + "|"]
    for row in rows:
        lines.append("| " + " | ".join("" if c is None else str(c) for c in row) + " |")
    return "\n".join(lines)


def _percent(value: float | None) -> str:
    return "—" if value is None else f"{value:.1%}"


def write_load_report(path: Path, result, corpus) -> None:
    coverage = result.coverage
    lines = [
        "# Load report — FHIR R4 → OMOP CDM v5.4",
        "",
        "Generated by `ofb load`, part of `ofb pipeline`. Do not edit by hand: CI "
        "compares the committed copy against a fresh run, so a stale number fails the "
        "build.",
        "",
        f"- **{sum(result.source_resource_counts.values()):,} FHIR resources** read from "
        f"{len(corpus.files)} file(s)",
        f"- **{sum(result.row_counts.values()):,} OMOP rows** written across "
        f"{sum(1 for v in result.row_counts.values() if v):,} tables",
        f"- **{result.surrogate_keys_minted:,} surrogate keys** minted and recorded in "
        "`bridge_source_map`",
        f"- concept map: **{result.concept_map_size:,} codings**, "
        f"{result.concept_map_provenance.get('vocabulary_source', 'unknown source')}",
        "",
        "## OMOP rows by table",
        "",
        _table(
            ["table", "rows"],
            [[t, f"{n:,}"] for t, n in result.row_counts.items() if n]
            + [["**total**", f"**{sum(result.row_counts.values()):,}**"]],
        ),
        "",
        "## Source resources: mapped, and deliberately not",
        "",
        _table(
            ["resource type", "in source", "OMOP rows produced", "status"],
            [
                [
                    rtype,
                    f"{count:,}",
                    f"{result.rows_by_source_type.get(rtype, 0):,}",
                    "mapped" if rtype in result.rows_by_source_type else "out of scope",
                ]
                for rtype, count in result.source_resource_counts.items()
            ],
        ),
        "",
        "Out-of-scope types are counted rather than dropped silently; `docs/limits.md` says why each",
        "is out of scope.",
        "",
        "## Terminology coverage",
        "",
        f"Overall mapped share: **{_percent(coverage.get('overall_mapped_share'))}** of code "
        f"lookups resolved to a non-zero standard concept. "
        f"{coverage.get('distinct_unmapped_codes', 0)} distinct codes did not resolve.",
        "",
        "### By target domain",
        "",
        _table(
            ["domain", "mapped", "unmapped", "mapped share"],
            [
                [domain or "(none)", f"{c['mapped']:,}", f"{c['unmapped']:,}",
                 _percent(c["mapped_share"])]
                for domain, c in (coverage.get("by_domain") or {}).items()
            ],
        ),
        "",
        "### By vocabulary",
        "",
        _table(
            ["vocabulary", "mapped", "unmapped", "mapped share"],
            [
                [vocab, f"{c['mapped']:,}", f"{c['unmapped']:,}", _percent(c["mapped_share"])]
                for vocab, c in (coverage.get("by_vocabulary") or {}).items()
            ],
        ),
        "",
        "A zero count in a domain whose mapped share is low is not evidence of absence. That is why",
        "this table exists and why it is printed before any counts are quoted.",
        "",
    ]
    if coverage.get("top_unmapped_codes"):
        lines += [
            "### Codes that did not resolve",
            "",
            _table(
                ["vocabulary", "code", "occurrences"],
                [
                    [c["vocabulary"], c["code"], f"{c['occurrences']:,}"]
                    for c in coverage["top_unmapped_codes"]
                ],
            ),
            "",
            "These are written as `concept_id = 0` with the source code retained on the row, so the",
            "mapping can be completed later without re-reading FHIR.",
            "",
        ]
    lines += [
        "## Observation domain routing",
        "",
        "FHIR `Observation` is split between OMOP MEASUREMENT and OBSERVATION. The basis for each",
        "decision is counted so the fallback share is visible rather than assumed.",
        "",
        _table(
            ["basis", "rows"],
            [[basis, f"{n:,}"] for basis, n in result.observation_routing.items()],
        ),
        "",
    ]
    if result.unresolved_references:
        lines += [
            "## References that did not resolve",
            "",
            _table(
                ["reference shape", "count"],
                [[shape, f"{n:,}"] for shape, n in sorted(result.unresolved_references.items())],
            ),
            "",
        ]
    if result.warnings:
        lines += ["## Warnings", ""] + [f"- {w}" for w in result.warnings] + [""]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8", newline="\n")


def write_validation_report(path: Path, results, ok: bool, errors: int, warnings: int) -> None:
    grouped: dict[str, list] = {}
    for result in results:
        grouped.setdefault(result.name, []).append(result)
    lines = [
        "# Conformance report — OMOP CDM v5.4",
        "",
        "Generated by `ofb check`, part of `ofb pipeline`. Do not edit by hand: CI "
        "compares the committed copy against a fresh run, so a stale number fails the "
        "build.",
        "",
        f"**Gate: {'PASS' if ok else 'FAIL'}** — {errors} error-severity check(s) failing, "
        f"{warnings} warning(s). CI fails the build on the first number.",
        "",
        "Structural checks are generated from the vendored OHDSI DDL: nullability, `varchar(n)`",
        "lengths, primary keys and foreign keys are read out of the specification rather than",
        "restated here, so they cannot drift from it.",
        "",
        _table(
            ["check", "checks run", "failing", "rows examined", "failures"],
            [
                [
                    name,
                    len(group),
                    sum(1 for r in group if not r.passed),
                    f"{sum(r.examined for r in group):,}",
                    f"{sum(r.failures for r in group):,}",
                ]
                for name, group in sorted(grouped.items())
            ],
        ),
        "",
    ]
    failing = [r for r in results if not r.passed]
    if failing:
        lines += [
            "## Failing checks",
            "",
            _table(
                ["check", "target", "severity", "failures", "examined", "examples"],
                [
                    [
                        r.name,
                        r.target,
                        r.severity,
                        f"{r.failures:,}",
                        f"{r.examined:,}",
                        ", ".join(str(e)[:40] for e in r.examples[:3]),
                    ]
                    for r in failing
                ],
            ),
            "",
        ]
    else:
        lines += ["Every generated and hand-written check passes on the committed sample.", ""]
    lines += [
        "## What each check asserts",
        "",
        _table(
            ["check", "assertion", "source"],
            [
                ["not_null", "no NULL in a NOT NULL column", "generated from DDL"],
                ["varchar_length", "no value longer than its declared varchar(n)", "generated from DDL"],
                ["primary_key_unique", "no duplicate primary key", "generated from primary_keys.sql"],
                [
                    "foreign_key_closure",
                    "every non-null foreign key resolves",
                    "generated from constraints.sql",
                ],
                [
                    "concept_id_declared",
                    "every non-zero concept_id came from the committed map or verified constants",
                    "hand-written (vocabulary tables are licence-gated)",
                ],
                ["temporal_order", "end date never precedes start date", "hand-written"],
                ["event_after_birth", "no event before date of birth", "hand-written"],
                [
                    "event_within_observation_period",
                    "no event outside the derived observation period",
                    "hand-written",
                ],
                [
                    "visit_person_consistency",
                    "an event's visit belongs to the event's person",
                    "hand-written",
                ],
                [
                    "death_not_before_last_event",
                    "death date not before the last event (warning)",
                    "hand-written",
                ],
                [
                    "person_has_observation_period",
                    "every person has an observation period (warning)",
                    "hand-written",
                ],
            ],
        ),
        "",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8", newline="\n")


def write_roundtrip_report(path: Path, comparison: dict, coverage_rows: list[dict], export) -> None:
    totals = comparison["totals"]
    lines = [
        "# Round-trip report — FHIR → OMOP → FHIR",
        "",
        "Generated by `ofb roundtrip`, part of `ofb pipeline`. Do not edit by hand: CI "
        "compares the committed copy against a fresh run, so a stale number fails the "
        "build.",
        "",
        f"- **{totals.get('compared', 0):,} field comparisons** across "
        f"{len(comparison['fields'])} resource types",
        f"- **{_percent(totals.get('retention'))} retained byte-identical**, "
        f"{_percent(totals.get('retention_including_transformed'))} retained or recoverably "
        "transformed",
        f"- **{totals.get('dropped', 0):,} comparisons** where OMOP had nowhere to put the value",
        "",
        "## Resource-level coverage",
        "",
        "Field fidelity is reported separately from resource coverage on purpose: a resource type",
        "that is never mapped records no field losses, which would flatter the mapper if the two",
        "were mixed together.",
        "",
        _table(
            ["resource type", "in source", "OMOP rows", "exported back", "mapped"],
            [
                [
                    r["resource_type"],
                    f"{r['in_source']:,}",
                    f"{r['omop_rows']:,}",
                    f"{r['exported']:,}",
                    "yes" if r["mapped"] else "no",
                ]
                for r in coverage_rows
            ],
        ),
        "",
        "## Field-level fidelity",
        "",
    ]
    for rtype, fields in comparison["fields"].items():
        lines += [
            f"### {rtype}",
            "",
            _table(
                ["field", "compared", "retained", "transformed", "dropped", "retention", "reason"],
                [
                    [
                        label,
                        f"{t['compared']:,}",
                        f"{t['retained']:,}",
                        f"{t['transformed']:,}",
                        f"{t['dropped']:,}",
                        _percent(t["retention"]),
                        "; ".join(t["reasons"]) or "—",
                    ]
                    for label, t in fields.items()
                ],
            ),
            "",
        ]
    lines += [
        "## Losses that are structural, not row-level",
        "",
        _table(
            ["what is lost", "why"],
            [[loss["item"], loss["explanation"]] for loss in comparison["structural_losses"]],
        ),
        "",
        "## Elements fabricated to satisfy FHIR cardinality",
        "",
        "FHIR requires these; the CDM does not store them. They are emitted from constants, and a",
        "reader is entitled to know which fields those are.",
        "",
        _table(
            ["element", "emitted value and reason"],
            [[k, v] for k, v in (export.fabricated_elements or {}).items()],
        ),
        "",
        "## Join outcomes",
        "",
        _table(
            ["outcome", "resources"],
            [[k, f"{v:,}"] for k, v in comparison["joins"].items()],
        ),
        "",
        "## Resource type transformations",
        "",
        _table(
            ["source → exported", "count"],
            [[k, f"{v:,}"] for k, v in comparison["resource_type_pairs"].items()],
        ),
        "",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8", newline="\n")


def write_json(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(payload, indent=2, default=str), encoding="utf-8", newline="\n"
    )


def write_server_validation_report(path: Path, summary: dict) -> None:
    """Kept separate from ``export-summary.json`` on purpose.

    This report depends on a running server, so it is written only when ``--fhir-server`` is given.
    That keeps the server-free pipeline's reports byte-stable, which is what lets CI fail the build
    when a committed number goes stale.
    """
    server = summary.get("server") or {}
    lines = [
        "# FHIR server validation",
        "",
        f"Generated by `ofb export --fhir-server {summary.get('endpoint', '')}`. "
        "Do not edit by hand.",
        "",
        f"- Server: **{server.get('software')} {server.get('softwareVersion')}**, "
        f"FHIR **{server.get('fhirVersion')}**",
        f"- **{summary.get('total_passed', 0):,} of {summary.get('total_validated', 0):,} resources "
        f"accepted**, {summary.get('total_failed', 0):,} rejected",
        "",
        "Every exported resource is submitted to the server's `$validate` operation, which checks it",
        "against the published R4 StructureDefinitions rather than against this project's own idea of",
        "the right shape. A resource counts as rejected if its OperationOutcome carries any issue of",
        "severity `error` or `fatal`.",
        "",
        _table(
            ["resource type", "validated", "passed", "failed"],
            [
                [rtype, f"{c['validated']:,}", f"{c['passed']:,}", f"{c['failed']:,}"]
                for rtype, c in (summary.get("by_type") or {}).items()
            ],
        ),
        "",
        "## Issue severities",
        "",
        _table(
            ["severity", "issues"],
            [[s, f"{n:,}"] for s, n in (summary.get("severity_totals") or {}).items()],
        ),
        "",
    ]
    if summary.get("top_non_blocking_issues"):
        lines += [
            "Warnings are not failures, and reporting only the total would hide what they are:",
            "",
            _table(
                ["occurrences", "diagnostics"],
                [
                    [f"{issue['occurrences']:,}", issue["diagnostics"]]
                    for issue in summary["top_non_blocking_issues"]
                ],
            ),
            "",
        ]
    if summary.get("failures"):
        lines += [
            "## Rejected resources",
            "",
            _table(
                ["resource type", "id", "issue"],
                [
                    [
                        failure["resourceType"],
                        failure["id"],
                        "; ".join(
                            f"{i['severity']}: {i['diagnostics']}" for i in failure["issues"]
                        ),
                    ]
                    for failure in summary["failures"]
                ],
            ),
            "",
        ]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8", newline="\n")
