"""Verify every hard-coded concept id against a live OHDSI vocabulary service.

``constants.py`` asserts vocabulary facts: that 8507 is MALE in the Gender domain, that 756265 names
CDM 5.4, that 32838 is "EHR prescription". Those assertions are the kind of thing that gets
remembered slightly wrong, and a wrong type concept is invisible -- the database loads, the checks
pass, and every row is mislabelled.

So the constants carry an expected name, domain and standard flag, and this script checks them. It
exits non-zero on any disagreement, runs in CI, and writes ``docs/reports/concept-id-verification.md``.

Usage:
    python scripts/verify_constants.py [--service https://atlas-demo.ohdsi.org/WebAPI]
"""

from __future__ import annotations

import argparse
import json
import sys
import urllib.request
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from omop_fhir_bridge.constants import VERIFIABLE  # noqa: E402

DEFAULT_SERVICE = "https://atlas-demo.ohdsi.org/WebAPI"
REPORT = Path(__file__).resolve().parents[1] / "docs" / "reports" / "concept-id-verification.md"


def lookup(service: str, concept_ids: list[int]) -> dict[int, dict]:
    request = urllib.request.Request(
        f"{service.rstrip('/')}/vocabulary/lookup/identifiers",
        data=json.dumps(concept_ids).encode(),
        headers={"Content-Type": "application/json", "Accept": "application/json"},
        method="POST",
    )
    with urllib.request.urlopen(request, timeout=90) as response:
        records = json.loads(response.read().decode())
    return {int(r["CONCEPT_ID"]): r for r in records}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--service", default=DEFAULT_SERVICE)
    parser.add_argument("--report", default=str(REPORT))
    args = parser.parse_args()

    found = lookup(args.service, sorted(VERIFIABLE))
    rows, failures = [], []
    for concept_id, (name, domain, standard) in sorted(VERIFIABLE.items()):
        record = found.get(concept_id)
        if record is None:
            status = "NOT FOUND"
            failures.append(f"{concept_id} not found in the vocabulary")
            rows.append((concept_id, name, domain, standard, "—", "—", "—", status))
            continue
        actual = (
            record.get("CONCEPT_NAME", ""),
            record.get("DOMAIN_ID", ""),
            record.get("STANDARD_CONCEPT") or "N",
        )
        mismatches = [
            f"{label}: expected {expected!r}, service says {got!r}"
            for label, expected, got in (
                ("name", name, actual[0]),
                ("domain", domain, actual[1]),
                ("standard", standard, actual[2]),
            )
            if expected != got
        ]
        status = "ok" if not mismatches else "MISMATCH"
        if mismatches:
            failures.append(f"{concept_id}: " + "; ".join(mismatches))
        rows.append((concept_id, name, domain, standard, *actual, status))

    lines = [
        "# Concept id verification",
        "",
        f"Generated by `scripts/verify_constants.py` on {date.today().isoformat()} against "
        f"`{args.service}`. Do not edit by hand.",
        "",
        f"**{len(rows) - len(failures)} of {len(rows)} hard-coded concept ids verified.**",
        "",
        "Every identifier in `constants.py` is listed with what the code claims about it and what a",
        "live OHDSI vocabulary service returns. Clinical codes are absent by design: they live in",
        "`vocab_data/concept_map.csv`, which is generated the same way.",
        "",
        "| concept_id | claimed name | claimed domain | std | service name | service domain | std | status |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for row in rows:
        lines.append("| " + " | ".join(str(c) for c in row) + " |")
    if failures:
        lines += ["", "## Disagreements", ""] + [f"- {f}" for f in failures]
    lines.append("")
    report_path = Path(args.report)
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text("\n".join(lines), encoding="utf-8")

    print(f"verified {len(rows) - len(failures)}/{len(rows)} concept ids -> {report_path}")
    for failure in failures:
        print(f"  MISMATCH {failure}")
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
